### ISSUE TITLE
Backwards Compatibility for API 5.1

### ISSUE THREAD

**Issue by deejballa** [jeffpriz/ado-wait-work-time#10]
When loading this plugin for our on prem instance we get the following error. Is it possible to get an instance that has backwards compatibility for API version of 5.1?
![image](https://user-images.githubusercontent.com/2600841/135356887-a5207768-426c-43c8-b9d7-76c55cc8a099.png)

**Comment by jeffpriz** [comment]
This extension is set up to use some of the more current API and UI libraries... It will work with  Azure DevOps Server 2020.1 (Vers 18.181.31425.1) or newer
