### ISSUE TITLE
Unable to find widget after install

### ISSUE THREAD

**Issue by bakerb5** [jeffpriz/ado-wait-work-time#17]
I have installed the widget into my ADO org, but I cannot find it in the available list of widgets for the dashboard.  Is there something I need to configure to make it available?

**Comment by jeffpriz** [comment]
It should show up for you no issues.  Once installed from the marketplace you should have it available on your AzDO under the boards, near the bottom of the choices in Boards

**Comment by bakerb5** [comment]
lol, I am such a dope.  I was looking for it as a dashboard widget.  Thank you!!!

**Comment by bakerb5** [comment]
lol, I am such a dope. I was looking for it as a dashboard widget. Thank you!!!

**Comment by jeffpriz** [comment]
No worries.  sorry for the confusion
